name: Publish
on: [push]
jobs:
  docker:
    name: publish docker
    runs-on: ubuntu-latest
    steps:
      - name: Update CA
        run: |
          sudo apt-get install --reinstall ca-certificates
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ambitionecho
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: ambitionecho/ubuntu-with-qt:latest
